name = "qleisli_kernel"
version = "0.2.8"
defaultTargets = ["QleisliKernel", "qleisli-kernel"]

[leanOptions]
autoImplicit = false
warningAsError = true

[[lean_lib]]
name = "QleisliKernel"
roots = ["QleisliKernel", "Protocol"]
globs = ["QleisliKernel.*", "Protocol.*", "Cli.+"]

[[lean_exe]]
name = "qleisli-kernel"
root = "Main"
